name = input("What is your full name? ")
address = input("What is your street address? ")
city = input("What is your city? ")
state = input("What is your state (please enter abbreviated form)? ")
zip_code = input("What is your zip code? ")
print(name)
print(address)
print(city + ", " + state + " " + zip_code)
